PYTHON=python3
BUBBLE=5 25 -50 50
QUICK=5 25 -50 50
MERGE=16 16 -50 50
RADIX=5 15 100 999
COUNT=5 25 0 10
INSRT=5 25 -50 50

bubble:
	@$(PYTHON) bubble.py $(BUBBLE)

insertion:
	@$(PYTHON) insertion.py $(INSRT)

quick:
	@$(PYTHON) quick.py $(QUICK)

merge:
	@$(PYTHON) merge.py $(MERGE)

counting:
	@$(PYTHON) counting.py $(COUNT)

radix:
	@$(PYTHON) radix.py $(RADIX)